lighttpd:  
  build: .
  dockerfile: ./lighttpd/Dockerfile

mysql:
  build: .
  dockerfile: ./mysql/Dockerfile
  links:
   - "lighttpd:lighttpd"

asterisk:
  build: .
  dockerfile: ./asterisk/Dockerfile
  links:
   - "lighttpd:lighttpd"
   - "mysql:mysql"

freepbx:
  build: .
  dockerfile: ./freepbx/Dockerfile
  ports:
    - "80"
    - "3306"
    - "5060-5070"
    - "10000-20000"
    - "19302-19309"
    - "8088"
    - "8080"
  links:
    - "lighttpd:lighttpd"
    - "mysql:mysql"
    - "asterisk:asterisk"
